### ISSUE TITLE
Doesn't work with IPython 2.0 dev

### ISSUE THREAD

**Issue by sglyon** [maximsch2/SublimeIPythonNotebook#25]
I recently installed IPython from the master branch because I wanted to test some new functionality (interactive widgets, chaining directory from dashboard, ect.)

There are at least a few things that have changed that break this plugin. I will list the ones I have found so far, but I am sure there are more.
- [ ] We can no longer get a list of notebook names like [this](https://github.com/maximsch2/SublimeIPythonNotebook/blob/master/ipy_connection.py#L39). we need `target_url = target_url = baseurl   + "/api/notebooks"`
- [ ] There are no longer any `notebook_id`s for an ipynb file . This changes a lot of things in the package.

---

**EDIT**

Most of the changes we need to worry about are documented here: https://github.com/ipython/ipython/wiki/IPEP-16%3A-Notebook-multi-directory-dashboard-and-URL-mapping

**Comment by divinites** [comment]
Now, Sublime Text has phantom support, which means it is possible to insert image now.

**Comment by maximsch2** [comment]
A version that can load and display (but not edit or execute) newest Jupyter notebooks (from the root path only) is in this branch: https://github.com/maximsch2/SublimeIPythonNotebook/tree/jupyter
No ETA on when (if ever) full functionality will be supported on newest jupyter.
